service: wolfram-lambda

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  timeout: 10
  memorySize: 128
  profile: psyfear

package:
  exclude:
    - test
    - docs

functions:
  wolfram:
    handler: handler.wolfram
    events:
      - http:
          method: post
          path: wolfram
          integration: lambda
          request:
            template:
              application/x-www-form-urlencoded: '{ "body": "$input.body" }'
